name: dask-mpi-docs
channels:
  - conda-forge 
  - nodefaults
dependencies:
  - dask>=2.19
  - distributed>=2.19
  - mpich
  - mpi4py>=3.0.3
  - versioneer
  - sphinx
  - pygments
  - pip
  - pip:
    - dask_sphinx_theme
    - numpydoc
    - sphinx-click
