name: dask-mpi-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python<3.12
  - dask>=2.19
  - distributed>=2.19
  - mpich
  - mpi4py>=3.0.3
  - versioneer
  - sphinx>=7
  - pygments
  - pip
  - pip:
      - dask-sphinx-theme>=4
      - numpydoc
      - sphinx-click
